/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TwoSpacesIndentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  maxIndentLevels: 10
};
var TwoSpacesIndentPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "increase-indent",
      name: "Increase indent",
      editorCallback: (editor, view) => {
        this.increaseIndent(editor);
      }
    });
    this.addCommand({
      id: "decrease-indent",
      name: "Decrease indent",
      editorCallback: (editor, view) => {
        this.decreaseIndent(editor);
      }
    });
    this.addSettingTab(new TwoSpacesIndentSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getIndentLevel(line) {
    let indent = 0;
    let i = 0;
    while (i < line.length && line[i] === " ") {
      indent++;
      i++;
    }
    return Math.floor(indent / 2);
  }
  increaseIndent(editor) {
    const selections = editor.listSelections();
    if (selections.length === 0)
      return;
    const lines = editor.getValue().split("\n");
    const processedLines = /* @__PURE__ */ new Set();
    let maxLevelReached = false;
    selections.forEach((selection) => {
      const startLine = selection.head.line;
      const endLine = selection.anchor.line;
      const minLine = Math.min(startLine, endLine);
      const maxLine = Math.max(startLine, endLine);
      for (let i = minLine; i <= maxLine; i++) {
        if (lines[i] !== void 0 && !processedLines.has(i)) {
          const currentIndent = this.getIndentLevel(lines[i]);
          if (currentIndent < this.settings.maxIndentLevels) {
            lines[i] = "  " + lines[i];
          } else {
            maxLevelReached = true;
          }
          processedLines.add(i);
        }
      }
    });
    editor.setValue(lines.join("\n"));
    const newSelections = selections.map((selection) => {
      const headLine = selection.head.line;
      const anchorLine = selection.anchor.line;
      const headCh = selection.head.ch;
      const anchorCh = selection.anchor.ch;
      const newHeadCh = headCh + 2;
      const newAnchorCh = anchorCh + 2;
      return {
        head: { line: headLine, ch: newHeadCh },
        anchor: { line: anchorLine, ch: newAnchorCh }
      };
    });
    editor.setSelections(newSelections);
    if (maxLevelReached) {
      new import_obsidian.Notice(`Maximum indent level (${this.settings.maxIndentLevels}) reached`);
    }
  }
  decreaseIndent(editor) {
    const selections = editor.listSelections();
    if (selections.length === 0)
      return;
    const lines = editor.getValue().split("\n");
    const processedLines = /* @__PURE__ */ new Set();
    let noIndentFound = true;
    selections.forEach((selection) => {
      const startLine = selection.head.line;
      const endLine = selection.anchor.line;
      const minLine = Math.min(startLine, endLine);
      const maxLine = Math.max(startLine, endLine);
      for (let i = minLine; i <= maxLine; i++) {
        if (lines[i] !== void 0 && !processedLines.has(i) && lines[i].startsWith("  ")) {
          lines[i] = lines[i].substring(2);
          processedLines.add(i);
          noIndentFound = false;
        }
      }
    });
    editor.setValue(lines.join("\n"));
    const newSelections = selections.map((selection) => {
      const headLine = selection.head.line;
      const anchorLine = selection.anchor.line;
      const headCh = selection.head.ch;
      const anchorCh = selection.anchor.ch;
      const newHeadCh = Math.max(0, headCh - 2);
      const newAnchorCh = Math.max(0, anchorCh - 2);
      return {
        head: { line: headLine, ch: newHeadCh },
        anchor: { line: anchorLine, ch: newAnchorCh }
      };
    });
    editor.setSelections(newSelections);
    if (noIndentFound) {
      new import_obsidian.Notice("No indentation to decrease");
    }
  }
};
var TwoSpacesIndentSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Two spaces indent settings").setHeading();
    new import_obsidian.Setting(containerEl).setName("Hotkeys").setDesc(
      `Hotkeys can be customized in Obsidian's Hotkeys settings. Search for "Increase indent" and "Decrease indent" commands.`
    );
    new import_obsidian.Setting(containerEl).setName("Maximum indent levels").setDesc("Maximum number of indent levels allowed (default: 10)").addSlider(
      (slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.maxIndentLevels).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxIndentLevels = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
